Move component namespace/new metadata
Sylius/SyliusResourceBundle pull request #774
Opened 2023-11-06 17:09 UTC by loic425

| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| License         | MIT

2023-11-06 20:07 UTC, oallain approved these changes
LGFM, but I don't know how to validate that everything is good, since it's a big search/replace.

2023-11-07 07:43 UTC, loic425 commented
> LGFM, but I don't know how to validate that everything is good, since it's a big search/replace.

Yes, these classes have been introduced in 1.11 so, they have no bc-layer to make.

2023-11-07 13:08 UTC, diimpp requested changes
I've browsed around 40%, will finish later this day

2023-11-07 13:08 UTC, diimpp commented on docs/resource_factories.md
> +use Sylius\Component\Resource\Model\ResourceInterface;use Sylius\Resource\Metadata\AsResource;use Sylius\Resource\Metadata\Create;
Please split on multiline.

2023-11-07 13:08 UTC, diimpp commented on docs/resource_factories.md
> +use Sylius\Component\Resource\Model\ResourceInterface;use Sylius\Resource\Metadata\AsResource;use Sylius\Resource\Metadata\Create;
Please split on multiline.

2023-11-07 13:08 UTC, diimpp commented on docs/resource_factories.md
> +use App\Factory\BookFactory;use Sylius\Component\Resource\Model\ResourceInterface;use Sylius\Resource\Metadata\AsResource;use Sylius\Resource\Metadata\Create;
Please split on multiline.

2023-11-07 13:08 UTC, diimpp commented on docs/resource_factories.md
> +use App\Factory\BookFactory;use Sylius\Resource\Metadata\AsResource;use Sylius\Resource\Metadata\Create;
Please split on multiline.

2023-11-07 13:08 UTC, diimpp commented on docs/redirect.md
>  use Sylius\Component\Resource\Model\ResourceInterface;
Missing `Create`

```php
use Sylius\Component\Resource\Metadata\Create;
```

2023-11-07 13:08 UTC, diimpp commented on docs/responders.md
> +use Sylius\Resource\Context\Context;
Please sort alphabetically.

2023-11-07 13:08 UTC, diimpp commented on src/Bundle/spec/Twig/Context/LegacyContextFactorySpec.php
>  use Sylius\Component\Resource\Metadata\MetadataInterface;
Shouldn't it be moved as well if other `Metadata` interfaces moved?

2023-11-07 13:08 UTC, diimpp commented on src/Component/Symfony/Routing/Factory/OperationRouteFactory.php
>  use Sylius\Component\Resource\Metadata\MetadataInterface;
Shouldn't it be moved as well?

2023-11-07 13:08 UTC, diimpp commented on src/Component/Symfony/Routing/Factory/OperationRouteFactoryInterface.php
>  use Sylius\Component\Resource\Metadata\MetadataInterface;
Shouldn't it be moved as well?

2023-11-07 13:10 UTC, diimpp commented on docs/redirect.md
>  use Sylius\Component\Resource\Model\ResourceInterface;
And
```patch
--- #[Resource]
+++ #[AsResource]
```

2023-11-07 13:27 UTC, loic425 commented on docs/redirect.md
>  use Sylius\Component\Resource\Model\ResourceInterface;
Fixed. I'm always impressed by your reviews. Thx.

2023-11-07 13:27 UTC, loic425 commented on docs/responders.md
> +use Sylius\Resource\Context\Context;
done

2023-11-07 13:29 UTC, loic425 commented on src/Bundle/spec/Twig/Context/LegacyContextFactorySpec.php
>  use Sylius\Component\Resource\Metadata\MetadataInterface;
It should but it has been introduced years ago, and should be part of another PR with a bc layer.

2023-11-07 16:17 UTC, diimpp commented on src/Bundle/Resources/config/services/metadata.xml
> +        <service id="sylius.resource_metadata_collection.factory.attributes" class="Sylius\Resource\Metadata\Resource\Factory\AttributesResourceMetadataCollectionFactory">
Not related to current PR, but this service has two aliases defined below.

![image](https://github.com/Sylius/SyliusResourceBundle/assets/870747/97cf9448-3870-4192-8aab-a308ecd38eb1)

I would probably make `id=Sylius\Resource\Metadata\Resource\Factory\ResourceMetadataCollectionFactoryInterface` main service and this `sylius.resource_metadata_collection.factory.attributes` as alias and deprecate other alias or all aliases.

2023-11-07 16:17 UTC, diimpp commented on src/Component/spec/Symfony/Routing/Factory/CollectionOperationRoutePathFactorySpec.php
> +        $operation = new \Sylius\Resource\Metadata\Api\GetCollection();
Please move definition to `use` list.

2023-11-07 16:17 UTC, diimpp commented on src/Component/spec/Symfony/Routing/Factory/CreateOperationRoutePathFactorySpec.php
> +        $operation = new \Sylius\Resource\Metadata\Api\Post();
Please move definition to `use` list.

2023-11-07 16:17 UTC, diimpp commented on src/Component/spec/Symfony/Routing/Factory/DeleteOperationRoutePathFactorySpec.php
> +        $operation = new \Sylius\Resource\Metadata\Api\Delete();
Please move definition to `use` list.

2023-11-07 16:17 UTC, diimpp commented on src/Component/spec/Symfony/Routing/Factory/DeleteOperationRoutePathFactorySpec.php
> +        $operation = new \Sylius\Resource\Metadata\Api\Delete(shortName: 'remove');
Please move definition to `use` list.

2023-11-07 16:17 UTC, diimpp commented on src/Component/spec/Symfony/Routing/Factory/ShowOperationRoutePathFactorySpec.php
> +        $operation = new \Sylius\Resource\Metadata\Api\Get();
Please move definition to `use` list.

2023-11-07 16:17 UTC, diimpp commented on src/Component/spec/Symfony/Routing/Factory/UpdateOperationRoutePathFactorySpec.php
> +        $operation = new \Sylius\Resource\Metadata\Api\Put();
Please move definition to `use` list.

2023-11-07 16:17 UTC, diimpp commented on src/Component/spec/Symfony/Routing/Factory/UpdateOperationRoutePathFactorySpec.php
> +        $operation = new \Sylius\Resource\Metadata\Api\Patch();
Please move definition to `use` list.

2023-11-07 16:17 UTC, diimpp commented on src/Component/src/Metadata/Operations.php
> +namespace  Sylius\Resource\Metadata;
```suggestion
namespace Sylius\Resource\Metadata;
```

2023-11-07 16:17 UTC, diimpp commented on tests/Application/src/Subscription/Entity/Subscription.php
> +#[\Sylius\Resource\Metadata\Api\GetCollection]
Please move this and bellow definitions to `use` list.

2023-11-07 16:17 UTC, diimpp commented on tests/Application/src/Subscription/Entity/Subscription.php
>  use Sylius\Component\Resource\Metadata\Api;
This `use` is probably not in use anymore

2023-11-07 16:49 UTC, loic425 commented on src/Bundle/Resources/config/services/metadata.xml
> +        <service id="sylius.resource_metadata_collection.factory.attributes" class="Sylius\Resource\Metadata\Resource\Factory\AttributesResourceMetadataCollectionFactory">
could we open an issue for that?

2023-11-07 19:14 UTC, diimpp commented on src/Bundle/Resources/config/services/metadata.xml
> +        <service id="sylius.resource_metadata_collection.factory.attributes" class="Sylius\Resource\Metadata\Resource\Factory\AttributesResourceMetadataCollectionFactory">
Done
https://github.com/Sylius/SyliusResourceBundle/issues/776

2023-11-07 19:17 UTC, diimpp commented on src/Component/spec/Symfony/Routing/Factory/ShowOperationRoutePathFactorySpec.php
> +        $operation = new \Sylius\Resource\Metadata\Api\Get();
@loic425 one case left

2023-11-07 19:41 UTC, loic425 commented on src/Component/spec/Symfony/Routing/Factory/ShowOperationRoutePathFactorySpec.php
> +        $operation = new \Sylius\Resource\Metadata\Api\Get();
oups sorry

2023-11-07 19:42 UTC, loic425 commented on src/Component/spec/Symfony/Routing/Factory/ShowOperationRoutePathFactorySpec.php
> +        $operation = new \Sylius\Resource\Metadata\Api\Get();
done @diimpp

2023-11-07 20:37 UTC, diimpp approved these changes

2023-11-08 08:17 UTC, lchrusciel approved these changes

2023-11-08 08:36 UTC, merged

2023-11-08 08:36 UTC, lchrusciel commented
Thank you, @loic425!