[phpspec-2-phpunit] migration of tests (StateMachine)
Sylius/SyliusResourceBundle pull request #955
Opened 2024-10-18 07:00 UTC by loic425

| Q               | A
| --------------- | -----
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets |
| License         | MIT

2025-06-25 16:13 UTC, diimpp approved these changes

2025-06-25 16:13 UTC, diimpp commented on src/Component/spec/StateMachine/OperationStateMachineSpec.php
> +use LogicException;
Should be used directly without global use.

2025-06-25 16:13 UTC, diimpp commented on src/Component/spec/StateMachine/OperationStateMachineSpec.php
> +        $this->expectException(LogicException::class);
```patch
---        $this->expectException(LogicException::class);
+++        $this->expectException(\LogicException::class);
```

2025-06-25 16:14 UTC, diimpp requested changes

2025-06-25 16:14 UTC, diimpp commented on src/Component/tests/StateMachine/State/ApplyStateMachineTransitionProcessorSpec.php
```
--- src/Component/tests/StateMachine/State/ApplyStateMachineTransitionProcessorSpec.php
+++ src/Component/tests/StateMachine/State/ApplyStateMachineTransitionProcessorTest.php
```

2025-06-26 08:38 UTC, mamazu commented on src/Component/tests/StateMachine/OperationStateMachineTest.php
> +    }
This can be removed as it would crash in the setup method if that was not the case.

2025-06-26 14:54 UTC, diimpp approved these changes

2025-06-26 14:56 UTC, diimpp commented on src/Component/tests/StateMachine/OperationStateMachineTest.php
> +    }
@mamazu sounds good, let's do it in a follow-up PR

2025-10-29 09:31 UTC, GSadee approved these changes

2025-10-29 09:31 UTC, merged